### ISSUE TITLE
Separate Repos for individual projects

### ISSUE THREAD

**Issue by HellerCommaA** [shekit/peeqo-robot#3]
Based on the reddit thread, you've obviously got a success on your hands. I'd suggest breaking this out into individual repositories (leaving this as the main source of knowledge). One for the code for the micros, one for the node server, one for the 3d files, etc. It'll help with people who want to contribute but don't need / want to download 3d files (for example).

**Comment by shekit** [comment]
Great idea. Will do that! Thanks

**Comment by HellerCommaA** [comment]
Looking forward to contributing!
