### ISSUE TITLE
Consider using Sonus

### ISSUE THREAD

**Issue by evancohen** [shekit/peeqo-robot#4]
Hey @shekit, love the project. Since you're already using the snowboy node module that I wrote I thought I would recommend [Sonus](https://github.com/evancohen/sonus): It uses snowboy for keyword spotting and has built-in streaming recognition, which might make things a little easier on you, given you are trying to open source.

I currently use it in an Electron project so you have something to base it off of: https://github.com/evancohen/smart-mirror

I'd be happy to send a PR if you'd care to point me in the right direction :)

**Comment by shekit** [comment]
hey @evancohen, love your project too.. still have to update this repo, been working in a test repo where I built the entire snowboy google integration only to find your library and realize you do it much better! so yes already switchin to Sonus on my test repo :)

**Comment by evancohen** [comment]
Awesome! If you need any help, either adding features to Sonus (or otherwise), I'd be happy to lend a hand.

I am super passionate about (and am trying to increase awareness around) voice interfaces. Would you mind linking to Sonus from your YouTube video/imgur post? That'd be really awesome :)

**Comment by shekit** [comment]
Done! Added to the imgur post under the voice recognition section :)

**Comment by evancohen** [comment]
Thanks! Once things cool down a bit for you (I imagine things are a bit crazy right now) it'd be really fun to collaborate on something. Ping me sometime!
