### ISSUE TITLE
Remove unneccessary `div`s in Pug/Jade files

### ISSUE THREAD

**Issue by riesinger** [shekit/peeqo-robot#6]
In Pug (or formerly Jade) you don't need to explicitly write `div(class="container")` (or something alike) but you could just prefix the class with a dot: `.container`. I think this makes the code less verbose and easier to read.

Discussion wanted 😄

**Comment by shekit** [comment]
Sorry! this repo is no longer maintained. Everything has been moved to https://github.com/shekit/peeqo where pug has been dropped entirely
