### ISSUE TITLE
Documentation of the architecture

### ISSUE THREAD

**Issue by assadollahi** [shekit/peeqo-robot#8]
Hi thanks für sharing this awesome project, it would be cool to understand the architecture better, like:

- what is the architecture from bird's eye view?
- what kind of speech recognition do you use (is it simply google or amazon?)
- what gif server do you query
- what is the main programming language (node,js, i guess, why not python?)
- what exactly do you do with bluetooth (or why is it necessary), to control the lamp?
- how do you manage dialogs (do you use a package like Jasper)
- how do you "load spotify" on the raspberry pi (i've seen projects doing that)
- it's nice that you use arduino for controlling the servos, but people need to know how to wire it up, at least roughly (i.e. how many servos do you use and what are their functions), pictures from the inside of the neck would be nice.

cheers, keep up the good work!

**Comment by shekit** [comment]
this has been moved to a new repo https://github.com/shekit/peeqo. If you have a look at the wiki it contains a tutorial on how to setup a custom command which covers a lot of these high level questions
